

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adhikari
      POSTGRES_DB: fastapi
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOSTNAME: db
      DATABASE_PORT: 5432
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: adhikari
    depends_on:
      - db

volumes:
  postgres_data:
